# Generated by Django 5.2.17 on 2026-09-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('timeframe', models.CharField(db_index=True, max_length=8)),
                ('strategy', models.CharField(db_index=True, default='testing1', max_length=64)),
                ('side', models.CharField(choices=[('LONG', 'LONG'), ('SHORT', 'SHORT')], max_length=8)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], db_index=True, default='OPEN', max_length=8)),
                ('signal_time', models.BigIntegerField(db_index=True)),
                ('entry_time', models.BigIntegerField(db_index=True)),
                ('entry_price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('risk_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('risk_per_share', models.DecimalField(decimal_places=6, max_digits=16)),
                ('stop_price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('best_price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('exit_time', models.BigIntegerField(blank=True, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('exit_reason', models.CharField(blank=True, max_length=32)),
                ('pnl', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-entry_time', '-id'],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'timeframe', 'strategy', 'side', 'signal_time'), name='unique_paper_signal')],
            },
        ),
    ]
