# Generated by Django 5.2.17 on 2026-09-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperWatchSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('timeframe', models.CharField(default='3m', max_length=8)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('last_signal_time', models.BigIntegerField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol', 'timeframe'],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'timeframe'), name='unique_paper_watch_symbol')],
            },
        ),
    ]
