# Generated by Django 5.2.17 on 2026-09-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_papertrade_contract_price_papertrade_delta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='broker_order_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='papertrade',
            name='broker_status',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='papertrade',
            name='execution_provider',
            field=models.CharField(db_index=True, default='local', max_length=32),
        ),
    ]
