# Generated by Django 5.2.17 on 2026-09-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_papertrade_broker_order_id_papertrade_broker_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionPaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underlying_symbol', models.CharField(db_index=True, max_length=32)),
                ('contract_symbol', models.CharField(db_index=True, max_length=64)),
                ('option_type', models.CharField(choices=[('call', 'call'), ('put', 'put')], max_length=8)),
                ('expiration_date', models.DateField(db_index=True)),
                ('strike', models.DecimalField(decimal_places=6, max_digits=16)),
                ('side', models.CharField(choices=[('LONG', 'LONG'), ('SHORT', 'SHORT')], max_length=8)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], db_index=True, default='OPEN', max_length=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('entry_price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('entry_underlying_price', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('entry_bid', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('entry_ask', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('entry_iv', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('entry_delta', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('entry_gamma', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('entry_theta', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('entry_vega', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('entry_rho', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('exit_underlying_price', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('pnl', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('notes', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-entry_time', '-id'],
            },
        ),
    ]
