# Generated by Django 5.2.17 on 2026-09-06 20:42

import dashboard.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_optionpapertrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('rule_text', models.TextField(default=dashboard.models.default_strategy_rule_text)),
                ('trade_asset', models.CharField(choices=[('underlying', 'underlying'), ('option', 'option')], db_index=True, default='option', max_length=16)),
                ('risk_percent', models.DecimalField(decimal_places=6, default=Decimal('0.020000'), max_digits=7)),
                ('option_min_dte', models.PositiveIntegerField(default=7)),
                ('option_max_dte', models.PositiveIntegerField(default=14)),
                ('option_strike_mode', models.CharField(choices=[('atm', 'atm'), ('itm', 'itm'), ('otm', 'otm')], default='atm', max_length=8)),
                ('option_take_profit_percent', models.DecimalField(blank=True, decimal_places=6, default=Decimal('1.000000'), max_digits=7, null=True)),
                ('option_stop_loss_percent', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.500000'), max_digits=7, null=True)),
                ('max_spread_percent', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.500000'), max_digits=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='optionpapertrade',
            name='auto_trade',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='optionpapertrade',
            name='exit_reason',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='optionpapertrade',
            name='signal_time',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='optionpapertrade',
            name='strategy',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='optionpapertrade',
            name='timeframe',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.CreateModel(
            name='StrategyScanState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('timeframe', models.CharField(max_length=8)),
                ('last_signal_time', models.BigIntegerField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_states', to='dashboard.strategy')),
            ],
            options={
                'ordering': ['strategy__name', 'symbol', 'timeframe'],
                'constraints': [models.UniqueConstraint(fields=('strategy', 'symbol', 'timeframe'), name='unique_strategy_scan_state')],
            },
        ),
    ]
