# Generated by Django 5.2.17 on 2026-09-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_strategy_optionpapertrade_auto_trade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.CharField(max_length=16)),
                ('action', models.CharField(max_length=16)),
                ('reason', models.CharField(max_length=64)),
                ('asset', models.CharField(max_length=16)),
                ('trade_id', models.BigIntegerField(blank=True, null=True)),
                ('strategy', models.CharField(blank=True, max_length=64)),
                ('snapshot', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
