# Generated by Django 5.2.17 on 2026-09-30 19:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_pineindicator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketAlertWorker',
            fields=[
                ('key', models.CharField(default='alerts', max_length=16, primary_key=True, serialize=False)),
                ('lease_owner', models.CharField(blank=True, max_length=64)),
                ('lease_until', models.DateTimeField(default=django.utils.timezone.now)),
                ('heartbeat_at', models.DateTimeField(null=True)),
                ('discord_retry_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('symbols', models.JSONField(default=list)),
                ('timeframes', models.JSONField(default=list)),
                ('condition', models.JSONField(default=dict)),
                ('cooldown_minutes', models.PositiveIntegerField(default=0)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('armed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MarketAlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=80)),
                ('symbol', models.CharField(max_length=32)),
                ('timeframe', models.CharField(max_length=8)),
                ('bar_time', models.BigIntegerField()),
                ('bar_closed_at', models.DateTimeField()),
                ('snapshot', models.JSONField(default=dict)),
                ('message', models.TextField()),
                ('status', models.CharField(db_index=True, default='pending', max_length=16)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('retry_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(null=True)),
                ('alert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.marketalert')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('alert', 'revision', 'symbol', 'timeframe', 'bar_time'), name='unique_market_alert_event')],
            },
        ),
        migrations.CreateModel(
            name='MarketAlertState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('timeframe', models.CharField(max_length=8)),
                ('last_bar_time', models.BigIntegerField(null=True)),
                ('checked_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='Waiting for scanner', max_length=160)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_states', to='dashboard.marketalert')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('alert', 'symbol', 'timeframe'), name='unique_market_alert_state')],
            },
        ),
    ]
